[platformio]
default_envs = m5cardputer_adv
src_dir = esp32_marauder
data_dir = esp32_marauder/data

[env:m5cardputer_adv]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
board_build.flash_size = 8MB
board_build.partitions = partitions_m5cardputer_adv.csv
lib_extra_dirs =
  libraries
  esp32_marauder/libraries
build_flags =
  -DESP32S3
  -DMARAUDER_CARDPUTER_ADV
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DCORE_DEBUG_LEVEL=0
  -Wl,-zmuldefs
  -DUSER_SETUP_LOADED
  -DCGRAM_OFFSET
  -DST7789_DRIVER
  -DTFT_RGB_ORDER=1
  -DTFT_WIDTH=135
  -DTFT_HEIGHT=240
  -DTFT_BL=38
  -DTFT_RST=33
  -DTFT_DC=34
  -DTFT_MOSI=35
  -DTFT_SCLK=36
  -DTFT_CS=37
  -DTOUCH_CS=-1
  -DTFT_BACKLIGHT_ON=HIGH
  -DLOAD_GLCD
  -DLOAD_FONT2
  -DLOAD_FONT4
  -DLOAD_FONT6
  -DLOAD_FONT7
  -DLOAD_FONT8
  -DLOAD_GFXFF
  -DSMOOTH_FONT
  -DSPI_FREQUENCY=20000000
  -DSPI_READ_FREQUENCY=20000000
  -DSPI_TOUCH_FREQUENCY=2500000
lib_deps =
  https://github.com/marian-craciunescu/ESP32Ping.git#1.6
  https://github.com/ESP32Async/AsyncTCP.git#v3.4.8
  https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.8.1
  https://github.com/stevemarple/MicroNMEA.git#v2.0.6
  https://github.com/plerup/espsoftwareserial.git#8.1.0
  https://github.com/Bodmer/TFT_eSPI.git#V2.5.34
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
  https://github.com/Bodmer/JPEGDecoder.git#1.8.0
  https://github.com/h2zero/NimBLE-Arduino.git#1.3.8
  https://github.com/adafruit/Adafruit_NeoPixel.git#1.12.0
  https://github.com/bblanchon/ArduinoJson.git#v6.18.2
  https://github.com/ivanseidel/LinkedList.git#v1.3.3
  https://github.com/adafruit/Adafruit_BusIO.git#1.15.0
  https://github.com/adafruit/Adafruit_MAX1704X.git#1.0.2
